### ISSUE TITLE
Looking to integrate this into current React Native Project. How would I go about using the SDK once I have everything on the react side set up.

### ISSUE THREAD

**Issue by aneagoie** [gigya/ReactNative-Demo#1]
Components are ready, but I need to add the `NativeModules.GigyaBridge` how would I go about doing this on an existing project? Is there a README update coming? Thank you

**Comment by gheerish** [comment]
Hey Andrei,

Are you able to email me at: gheerish.bansoodeb@gigya-inc.com and i'll send
you some guides.

cheers
Gheerish

**Comment by aneagoie** [comment]
Thanks will do!

**Comment by aneagoie** [comment]
I have emailed you with questions.

**Comment by georgekqi** [comment]
Hi Gheerish:
 Could you send me some document about how to use NativeModules.GigyaBridge in react-native app programming?

George Qi
qi.george@gmail.com
