### ISSUE TITLE
Did anyone face this issue on Iphone 6s with this project ?

### ISSUE THREAD

**Issue by sujeshkumaruv** [gigya/ReactNative-Demo#2]
<img width="320" alt="screen shot 2017-08-31 at 6 06 57 pm" src="https://user-images.githubusercontent.com/1913675/29925846-41978df2-8e7f-11e7-9cf1-0fc250adee90.png">

This is what happens when we click on facebook, twitter or googleplus icon on the opening page.

**Comment by gheerish** [comment]
It seems that Xcode is not reading/compiling the class: UIViewController+Utils.h and UIViewController+Utils.m

To fix, open the Xcode - workspace gigyareactnative.xcworkspace - then in Project View - Add files - then browse to: /ios/gigyareactnative/ and add the 2 missing files + build

**Comment by sujeshkumaruv** [comment]
Thank you , Ghreerish. This worked.

**Comment by sujeshkumaruv** [comment]
Also can you share an integration guide with me for android and ios that can help my team out with this task? 

Thanks.

**Comment by gheerish** [comment]
Hi - we don't really have a guide for React-Native, as we are using the native objective-c sdk for ios for e.g., and wrote a custom Bridge file to interface the sdk's native method.

The following project will show how the native flows for Gigya can be implemented - and then the Bridge file can be extended to implement these methods: https://github.com/gigya/iOS10Demo/blob/master/MyGigya/GigyaNativeViewController.m 

More information on the configuration and instructions are available here:
https://developers.gigya.com/display/GD/iOS

**Comment by alejandromcsd** [comment]
@sujeshkumaruv We have also updated the [README](https://github.com/gigya/ReactNative-Demo#existing) with some additional instructions. I hope this helps your team with the integration.
