### ISSUE TITLE
Can social login via Instagram possible with this? If no, is there any alternate method for doing it? 

### ISSUE THREAD

**Issue by TheIndianRaj** [gigya/ReactNative-Demo#4]

**Comment by alejandromcsd** [comment]
Hi @TheIndianRaj. Yes, please follow these steps:

1) If you don't have an Instagram social application, follow these instructions for set up, register in the Gigya Console and Instagram approval:
https://developers.gigya.com/display/GD/Instagram

2) Use the existing "[gigya.SocialLogin](https://github.com/gigya/ReactNative-Demo/blob/d3db4a8f90fc9fd9561463bcd3257011c92ddff4/components/SignIn.js#L20)" bridge method, passing "instagram" as the provider.

**Comment by TheIndianRaj** [comment]
Thanks, @alejandromcsd . That was helpful. 

(Sorry for the delay)

**Comment by sujeshkumaruv** [comment]
@alejandromcsd I tried the instagram login but after I login , this is giving me an account registration pending error. Are there any additional settings to be done? Any pointers in this direction will be appreciated. 
![img_4781](https://user-images.githubusercontent.com/1913675/33671687-4ab61836-dace-11e7-9d75-8583c25e9232.PNG)

**Comment by alejandromcsd** [comment]
@sujeshkumaruv "Account Pending Registration" probably means that your Schema requires a field that isn't retrieved by Instagram (i.e. profile.email). You should capture require information with a "Registration Completion" screen

**Comment by sujeshkumaruv** [comment]
@alejandromcsd : For someone to have the "Registration completion" screen, the gigya must return the registration token. We get it when we are trying to do fb login and then using the same reg token , we complete the registration. In this case , we only get the string "Account Pending Registration" error from Gigya. The same error appears when we use the React-Native Demo code here.
