### ISSUE TITLE
iOS App Facebook/Twitter login always shows an error "Account Pending Registration" 

### ISSUE THREAD

**Issue by TheIndianRaj** [gigya/ReactNative-Demo#5]
A facebook/twitter login in an iOS app which is set up as per the instructions [here](https://github.com/gigya/ReactNative-Demo#integrating-gigya-with-existing-projects). Everytime I try to log in through it, I get a message "Account Pending Registration". (_Only this string as an error_) 

I understand about the error from [here](https://developers.gigya.com/display/GD/Accounts+API%20#AccountsAPI-ErrorCodesandMessages). 

It's described as followed.

**_When is this Error Returned?_**
_The "Account pending verification" error (code 206002) is returned when the account has already been verified, and a user tries to log in with a loginID (usually an email address) that we have not yet verified that actually belongs to this person.  
When the accountOptions policy states that  verifyEmail  is "true", the account must be validated by using the available email addresses. When the policy states that  allowUnverifiedLogin  is "false", users are not allowed to login before they have verified their emails. So, in this case, when a user tries to login, and his account has not been verified yet, and verifyEmail is "true" in the policy and  allowUnverifiedLogin  is "false" in the policy, the "Account pending verification" error is returned._

**_What's the Expected Next Step?_** 
_Call accounts.resendVerificationCode to resend a validation email to the unverified addresses associated with the account. The email format is according to the templates defined in the policy._

I don't know how to set **verifyEmail** to false or **allowUnverifiedLogin** to true. I tried [accounts.setPolicies REST](https://developers.gigya.com/display/GD/accounts.setPolicies+REST), but failed to get anything positive. I would like not to resend a validation email to the unverified addresses. 

What should I do?

**Comment by alejandromcsd** [comment]
Hi, could you please confirm if you are getting a "Account Pending Registration" or a "Account pending verification"?

For Account Pending Registration: Make sure all the schema required fields are captured as part of the registration or profile completion screen.

For Account Pending Verification: You should only get this error if "[Email verification](https://developers.gigya.com/display/GD/Policies#Policies-email_verificationEmailVerification)" is enabled in your Policies. You can disable it via Gigya Console (Policies) or via accounts.setPolicies (verifyEmail=false).

**Comment by romainGorrias** [comment]
Please only raise issues related to this Github repository. For any API related problem you can always refer to developers.gigya.com, or contact Gigya Support
