### ISSUE TITLE
Can I implement the socialize.addConnection endpoint via this bridge? 

### ISSUE THREAD

**Issue by TheIndianRaj** [gigya/ReactNative-Demo#6]
I want to add multiple social media connection in a single account. Can I implement it using this gigya bridge?

**Comment by TheIndianRaj** [comment]
Any update on this?

**Comment by alejandromcsd** [comment]
@TheIndianRaj could you please provide more details on what are you trying to do? If you are referring to "[Account Linking](https://developers.gigya.com/display/GD/Linking+Social+Accounts)" then yes, it can be implemented with this Bridge. Are you implementing all your screens Native with React or using Screen-Sets?

**Comment by TheIndianRaj** [comment]
@alejandromcsd Thanks for your response. 

I am have added social login via gigya to my app(both in iOS and Android). I have also implemented the "Account Linking" part. And yes, I have implemented all my screens Native with React.

The app has options for regular email login and login via 4 social media. After I have logged in to an account, I want to link multiple social media accounts to the same account. I assume it is possible through the[ socialize.addConnection](https://developers.gigya.com/display/GD/socialize.addConnection+REST) endpoint. 

Is there a way to implement this endpoint via the Gigya Bridge?

**Comment by alejandromcsd** [comment]
@TheIndianRaj Gigya Bridge is nothing but a wrapper for iOS or Android native code. You should be able to wrap any operation supported by Gigya's iOS SDK or Android SDK via bridge (implementing a new method).

Gigya iOS SDK supports adding/removing connections:
![image](https://user-images.githubusercontent.com/9474865/34803222-36296698-f6c6-11e7-9f6d-c5df236153ac.png)

Also is the case for Android SDK:
![image](https://user-images.githubusercontent.com/9474865/34803284-8fc905aa-f6c6-11e7-957c-77995c0efb93.png)


Please refer to iOS/Android SDK documentation:
https://developers.gigya.com/display/GD/iOS+SDK+Reference
https://developers.gigya.com/display/GD/Android+SDK+Reference

**Comment by TheIndianRaj** [comment]
@alejandromcsd Thank you. 

But I implemented the addConnectionToProvider in a new method in the iOS bridge. The method looks like this.

`RCT_EXPORT_METHOD(addConnection:(NSString *)provider callback:(RCTResponseSenderBlock)callback) {
  
  NSMutableDictionary *parameters = [NSMutableDictionary dictionary];
  
  [Gigya addConnectionToProvider:provider
                      parameters:parameters
                            over:[UIViewController currentViewController]
               completionHandler:^(GSUser * _Nullable user, NSError * _Nullable error) {
    if (error) {
      if(user){
        callback(@[user.JSONString, [NSNull null]]);
      }
      else {
        NSDictionary *userInfo = [error userInfo];
        callback(@[userInfo, [NSNull null]]);
      }
    }
    else {
      if(user){
        callback(@[user.JSONString, [NSNull null]]);
      }
    }
  }];
  
}` 

As per the documentation, 

> When the user completes the login process, Gigya will associate the connection with the user’s account.

But I am getting the user information of the currently logged in user as the response for this method and also the social media connection is not associated.

I am not sure whether this comes under the scope of this repository. But if you can find what I did wrong here, that would be of great help.

**Comment by alejandromcsd** [comment]
@TheIndianRaj Have you tried doing a getAccountInfo on the user AFTER the connection is added?

It works fine for me. I have added the addConnection functionality in the latest commit. Please pull and verify.

![image](https://user-images.githubusercontent.com/9474865/34861152-dd804330-f7b6-11e7-8857-35606fa2eb7f.png)

**Comment by TheIndianRaj** [comment]
@alejandromcsd : The method worked! I can't thank you enough for this!!! Thanks a ton!!!

I have a small concern though. When I login through the SDK the addConnection method works fine. But if I try to live reload and try adding connection, this error in the screenshot pops up. 

Do you think this would be a problem, when the app is in the release mode? That is, is it a problem only in the debug mode?

![simulator screen shot 15-jan-2018 2 26 31 am](https://user-images.githubusercontent.com/17278053/34920660-058cd712-f99c-11e7-91d1-e1b854524f77.png)

**Comment by TheIndianRaj** [comment]
@alejandromcsd Any updates?

**Comment by alejandromcsd** [comment]
@TheIndianRaj could you create a new issue in the repo and add some steps to reproduce with Live Reload? It seems like Live Reload is not able to maintain the session information, I don't have reasons to believe this would be an issue you'll see while running app on prod - device.
