### ISSUE TITLE
Social login (google plus, twitter, instagram) not redirecting back to the app in Android.

### ISSUE THREAD

**Issue by TheIndianRaj** [gigya/ReactNative-Demo#7]
My app uses this repository for social login. It has Facebook, Twitter, Google Plus and Instagram logins. The iOS version works fine, but in the android version, after the completion of login process, it is not redirected back to the app. The app is stuck in the browser (See the screenshot).

Cross checked the setup process many times. But still no luck. What can be the possible issue here?

![screenshot_2018-01-20-11-58-51-428_com android chrome_1024](https://user-images.githubusercontent.com/17278053/35180729-8f758990-fddb-11e7-97d0-11f3b1ba99fb.png)

**Comment by TheIndianRaj** [comment]
@alejandromcsd Any insights on what may be causing this behaviour?

**Comment by alejandromcsd** [comment]
@TheIndianRaj sorry for the delay, please remember that this repository, as mentioned in the description, is provided for demo purposes "as-is", this is not an official Gigya support channel. I'll try to reproduce the issue this week and let you know.

**Comment by TheIndianRaj** [comment]
Closing this issue as the problem was with the package name of the app. The package name contained uppercase alphabets and social login redirected to the same package name, but with all the alphabets in lowercase. 

Thanks.
